import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Calculator } from "lucide-react";
import { getCurrentContext } from "@/lib/auth/current-context";
import { calculateMarketplaceProfitability, marketplaceFeeConfigs, type MarketplaceCode } from "@/lib/marketplace-profitability";
import { createClient } from "@/lib/supabase/server";
export default async function ProfitabilityPage({ params, searchParams }: { params: Promise<{ id: string; productId: string }>; searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  const { id, productId } = await params, query = await searchParams;
  const { workspace } = await getCurrentContext(); const supabase = await createClient();
  const { data: product } = await supabase.from("supplier_catalog_products").select("*,suppliers(name)").eq("id", productId).eq("integration_id", id).eq("workspace_id", workspace.id).maybeSingle();
  if (!product) notFound();
  const marketplace = (typeof query.marketplace === "string" && query.marketplace in marketplaceFeeConfigs ? query.marketplace : "amazon-fr") as MarketplaceCode;
  const target = Number(query.price) || Number(product.recommended_retail_price) || Number(product.purchase_price_ex_vat) * 2;
  const result = calculateMarketplaceProfitability({ productCostExVat: Number(product.purchase_price_ex_vat), shippingCostExVat: Number(product.shipping_cost ?? 0), salePriceIncVat: target, marketplace });
  return <div className="mx-auto max-w-4xl"><Link href={`/app/intelligence/fournisseurs/${id}`} className="inline-flex items-center gap-2 text-sm text-[#74756e]"><ArrowLeft className="size-4" />Catalogue</Link><header className="mt-5"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#75806e]">Estimation indépendante</p><h1 className="mt-2 text-3xl font-semibold">{product.title}</h1></header><div className="mt-7 grid gap-6 lg:grid-cols-[1fr_320px]"><section className="rounded-2xl border bg-white p-6"><form className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-medium">Marketplace<select name="marketplace" defaultValue={marketplace} className="mt-2 h-11 w-full rounded-xl border px-3 text-sm">{Object.entries(marketplaceFeeConfigs).map(([code,config]) => <option key={code} value={code}>{config.label}</option>)}</select></label><label className="text-xs font-medium">Prix de vente cible<input name="price" type="number" min="0" step=".01" defaultValue={target.toFixed(2)} className="mt-2 h-11 w-full rounded-xl border px-3 text-sm" /></label><button className="h-11 rounded-xl bg-[#20211d] text-sm font-medium text-white sm:col-span-2">Recalculer</button></form><p className="mt-6 rounded-xl bg-[#fff9e9] p-4 text-xs leading-5 text-[#75684b]">Les frais « {result.feeLabel} » sont des estimations configurées, pas des valeurs issues d’une API officielle.</p></section><section className="rounded-2xl border border-[#dce1d8] bg-[#eef1eb] p-5"><Calculator className="size-5" /><dl className="mt-4 space-y-3 text-sm">{[["Marge nette estimée",result.estimatedNetMargin],["Marge",result.marginPercent],["ROI",result.roi],["Prix minimum",result.minimumSalePrice],["Prix conseillé",result.recommendedSalePrice],["Trésorerie nécessaire",result.requiredCash]].map(([label,value]) => <div key={String(label)} className="flex justify-between gap-3"><dt>{label}</dt><dd className="font-semibold">{String(label).includes("Marge") && label === "Marge" || label === "ROI" ? `${Number(value).toFixed(1)} %` : new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(Number(value))}</dd></div>)}</dl></section></div></div>;
}
