import "server-only";
import { ebayHosts, getEbayApplicationToken } from "./auth";
import { EbayAuthenticationError, EbayInvalidResponseError, EbayRateLimitError, EbayUnavailableError } from "./errors";
import { ebayItemResponseSchema, ebaySearchResponseSchema } from "./schemas";
export type EbayBrowseSearch = { keywords?: string; gtin?: string; categoryId?: string; limit?: number; offset?: number };
export class EbayBrowseClient {
  constructor(private readonly fetcher: typeof fetch = fetch, private readonly timeoutMs = 15_000) {}
  private async request(path: string, parameters: Record<string,string|number|undefined>) { const token = await getEbayApplicationToken(this.fetcher); const url = new URL(path, ebayHosts().api); Object.entries(parameters).forEach(([key,value]) => { if (value !== undefined && value !== "") url.searchParams.set(key,String(value)); }); const controller = new AbortController(), timeout = setTimeout(() => controller.abort(), this.timeoutMs); let response: Response; try { response = await this.fetcher(url, { headers: { authorization: `Bearer ${token}`, "x-ebay-c-marketplace-id": process.env.EBAY_MARKETPLACE_ID || "EBAY_FR", "x-ebay-c-enduserctx": "contextualLocation=country%3DFR", accept: "application/json" }, signal: controller.signal, cache: "no-store" }); } catch { throw new EbayUnavailableError(); } finally { clearTimeout(timeout); } if (response.status === 401 || response.status === 403) throw new EbayAuthenticationError("Accès eBay refusé ou en attente."); if (response.status === 429) throw new EbayRateLimitError(); if (response.status >= 500) throw new EbayUnavailableError(); if (!response.ok) throw new EbayInvalidResponseError(`eBay a répondu HTTP ${response.status}.`); return response.json().catch(() => { throw new EbayInvalidResponseError(); }); }
  async search(input: EbayBrowseSearch) { const filter = "priceCurrency:EUR,deliveryCountry:FR"; const payload = await this.request("/buy/browse/v1/item_summary/search", { q: input.keywords, gtin: input.gtin, category_ids: input.categoryId, limit: Math.min(input.limit ?? 20, 200), offset: input.offset ?? 0, filter }); const parsed = ebaySearchResponseSchema.safeParse(payload); if (!parsed.success) throw new EbayInvalidResponseError(); return parsed.data; }
  async getItem(itemId: string) { const payload = await this.request(`/buy/browse/v1/item/${encodeURIComponent(itemId)}`, {}); const parsed = ebayItemResponseSchema.safeParse(payload); if (!parsed.success) throw new EbayInvalidResponseError(); return parsed.data; }
}
