import { EbayBrowseClient } from "./client";
import { normalizeEbayListing } from "./normalize";
import type { EbayMarketMetrics, EbaySearchStrategy, ListingMatch, MarketplaceMatchLevel, NormalizedMarketplaceListing } from "./types";
type SupplierProduct = { title: string; sku: string; ean: string | null; gtin: string | null; brand: string | null; category: string | null };
const normalizedText = (value: string | null) => (value ?? "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
function titleSimilarity(left: string, right: string) { const a = new Set(normalizedText(left).split(" ").filter(Boolean)), b = new Set(normalizedText(right).split(" ").filter(Boolean)); if (!a.size || !b.size) return 0; const common = [...a].filter((word) => b.has(word)).length; return common / Math.max(a.size,b.size); }
export function scoreEbayMatch(product: SupplierProduct, listing: NormalizedMarketplaceListing): ListingMatch { let score = 0; const reasons: string[] = [], warnings: string[] = []; const sourceGtin = product.ean || product.gtin; const listingGtin = listing.ean || listing.gtin; if (sourceGtin && listingGtin && sourceGtin === listingGtin) { score += 60; reasons.push("EAN/GTIN exact"); } else if (sourceGtin) warnings.push("EAN/GTIN non confirmé"); if (product.brand && listing.brand && normalizedText(product.brand) === normalizedText(listing.brand)) { score += 15; reasons.push("Marque exacte"); } if (product.sku && normalizedText(listing.title).includes(normalizedText(product.sku))) { score += 10; reasons.push("Référence exacte"); } const similarity = titleSimilarity(product.title, listing.title); score += Math.round(similarity * 20); if (similarity >= .6) reasons.push("Titre similaire"); if (product.category && listing.categoryName && normalizedText(listing.categoryName).includes(normalizedText(product.category))) { score += 5; reasons.push("Catégorie compatible"); } if (!listing.condition) warnings.push("État non renseigné"); score = Math.min(100,score); const level: MarketplaceMatchLevel = score >= 90 ? "exact" : score >= 70 ? "strong" : score >= 45 ? "possible" : "weak"; return { listing, matchScore: score, level, reasons, warnings }; }
export function calculateEbayMetrics(matches: ListingMatch[]): EbayMarketMetrics { const reliable = matches.filter((match) => match.level === "exact" || match.level === "strong"); const prices = reliable.map((match) => match.listing.totalDeliveredPrice ?? match.listing.price).sort((a,b) => a-b); const shipping = reliable.map((match) => match.listing.shippingCost).filter((value): value is number => value !== null); const average = (values:number[]) => values.length ? values.reduce((sum,value) => sum+value,0)/values.length : null; const median = prices.length ? (prices[Math.floor((prices.length-1)/2)] + prices[Math.ceil((prices.length-1)/2)])/2 : null; return { resultCount: matches.length, reliableResultCount: reliable.length, minimumPrice: prices[0] ?? null, medianPrice: median, averagePrice: average(prices), maximumPrice: prices.at(-1) ?? null, averageKnownShipping: average(shipping), freeShippingCount: reliable.filter((match) => match.listing.shippingCost === 0).length, newCount: reliable.filter((match) => normalizedText(match.listing.condition).includes("new") || normalizedText(match.listing.condition).includes("neuf")).length, usedCount: reliable.filter((match) => normalizedText(match.listing.condition).includes("used") || normalizedText(match.listing.condition).includes("occasion")).length, retrievedAt: new Date().toISOString() }; }
export function createEbaySearchPlan(product: SupplierProduct): { strategy: EbaySearchStrategy; query: string } { const gtin = product.ean || product.gtin; if (gtin) return { strategy: "gtin", query: gtin }; if (product.brand && product.sku) return { strategy: "brand_reference", query: `${product.brand} ${product.sku}` }; return { strategy: "title", query: product.title.replace(/\s+/g," ").trim() }; }
export class EbayMarketplaceService { constructor(private readonly client = new EbayBrowseClient()) {} async research(product: SupplierProduct) { const { strategy, query } = createEbaySearchPlan(product); const response = strategy === "gtin" ? await this.client.search({gtin:query,limit:30}) : await this.client.search({keywords:query,limit:30}); const marketplaceId=process.env.EBAY_MARKETPLACE_ID||"EBAY_FR"; const matches=response.itemSummaries.map((item) => scoreEbayMatch(product,normalizeEbayListing(item,marketplaceId))); return { strategy,query,matches,metrics:calculateEbayMetrics(matches) }; } }
