import { ebayItemResponseSchema, normalizedMarketplaceListingSchema } from "./schemas";
import type { NormalizedMarketplaceListing } from "./types";
function aspect(payload: { localizedAspects?: { name: string; value: string }[] }, names: string[]) { return payload.localizedAspects?.find((item) => names.includes(item.name.toLowerCase()))?.value ?? null; }
export function normalizeEbayListing(input: unknown, marketplaceId: string): NormalizedMarketplaceListing {
  const payload = ebayItemResponseSchema.parse(input);
  const shipping = payload.shippingOptions[0];
  const price = Number(payload.price.value);
  const shippingCost = shipping?.shippingCost ? Number(shipping.shippingCost.value) : null;
  return normalizedMarketplaceListingSchema.parse({ marketplace: "ebay", marketplaceId, externalId: payload.itemId, legacyItemId: payload.legacyItemId ?? null, title: payload.title, subtitle: payload.subtitle ?? payload.shortDescription ?? null, itemWebUrl: payload.itemWebUrl ?? null, imageUrl: payload.image?.imageUrl ?? null, additionalImages: payload.additionalImages.map((image) => image.imageUrl), sellerUsername: payload.seller?.username ?? null, sellerFeedbackPercentage: payload.seller?.feedbackPercentage ? Number(payload.seller.feedbackPercentage) : null, sellerFeedbackScore: payload.seller?.feedbackScore ?? null, price, currency: payload.price.currency, shippingCost, totalDeliveredPrice: shippingCost == null ? null : price + shippingCost, condition: payload.condition ?? null, buyingOptions: payload.buyingOptions, categoryId: payload.categories[0]?.categoryId ?? null, categoryName: payload.categories[0]?.categoryName ?? null, brand: aspect(payload, ["brand", "marque"]), gtin: aspect(payload, ["gtin"]), ean: aspect(payload, ["ean"]), available: payload.estimatedAvailabilities?.[0]?.estimatedAvailabilityStatus ? payload.estimatedAvailabilities[0].estimatedAvailabilityStatus !== "OUT_OF_STOCK" : null, estimatedDeliveryMin: shipping?.minEstimatedDeliveryDate ?? null, estimatedDeliveryMax: shipping?.maxEstimatedDeliveryDate ?? null, itemLocationCountry: payload.itemLocation?.country ?? null, returnsAccepted: payload.returnTerms?.returnsAccepted ?? null, rawData: payload, retrievedAt: new Date().toISOString() });
}
