import Link from "next/link";
import Image from "next/image";
import { notFound } from "next/navigation";
import { AlertCircle, ArrowLeft, BarChart3, Box, RefreshCw, Search, ShieldCheck } from "lucide-react";
import { StatusPill } from "@/components/app/page-shell";
import { getCurrentContext } from "@/lib/auth/current-context";
import { calculateElrovaProductScore } from "@/lib/product-intelligence/score";
import type { SupplierCapabilities } from "@/lib/supplier-intelligence/schemas";
import { createClient } from "@/lib/supabase/server";

const money = new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" });
function firstProductImage(value: unknown) {
  return Array.isArray(value) && typeof value[0] === "string" ? value[0] : null;
}
export default async function SupplierIntegrationDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  const { id } = await params, filters = await searchParams;
  const { workspace } = await getCurrentContext();
  const supabase = await createClient();
  const { data: integration } = await supabase.from("supplier_integrations").select("*,suppliers(*)").eq("id", id).eq("workspace_id", workspace.id).maybeSingle();
  if (!integration) notFound();
  const q = typeof filters.q === "string" ? filters.q.replace(/[,%()]/g, " ") : "";
  const category = typeof filters.category === "string" ? filters.category : "";
  const stockFilter = typeof filters.stock === "string" ? filters.stock : "";
  const maxPrice = Number(filters.maxPrice) || 0, maxDelay = Number(filters.maxDelay) || 0;
  let catalogQuery = supabase.from("supplier_catalog_products").select("*").eq("workspace_id", workspace.id).eq("integration_id", id).order("title").limit(100);
  if (q) catalogQuery = catalogQuery.or(`title.ilike.%${q}%,sku.ilike.%${q}%,ean.ilike.%${q}%,gtin.ilike.%${q}%,brand.ilike.%${q}%,category.ilike.%${q}%`);
  if (category) catalogQuery = catalogQuery.eq("category", category);
  if (stockFilter === "available") catalogQuery = catalogQuery.gt("stock", 0);
  if (stockFilter === "low") catalogQuery = catalogQuery.gt("stock", 0).lte("stock", 5);
  if (stockFilter === "out") catalogQuery = catalogQuery.eq("stock", 0);
  if (filters.eu === "true") catalogQuery = catalogQuery.in("ships_from_country", ["FR","DE","NL","PL","ES","IT","BE","PT","CZ","AT"]);
  if (filters.moq === "true") catalogQuery = catalogQuery.eq("moq", 1);
  if (maxPrice) catalogQuery = catalogQuery.lte("purchase_price_ex_vat", maxPrice);
  if (maxDelay) catalogQuery = catalogQuery.lte("delivery_max_days", maxDelay);
  const [{ data: products }, { data: runs }, { data: categoryRows }] = await Promise.all([
    catalogQuery, supabase.from("supplier_sync_runs").select("*").eq("workspace_id", workspace.id).eq("integration_id", id).order("started_at", { ascending: false }).limit(8),
    supabase.from("supplier_catalog_products").select("category").eq("workspace_id", workspace.id).eq("integration_id", id),
  ]);
  const supplier = Array.isArray(integration.suppliers) ? integration.suppliers[0] : integration.suppliers;
  const capabilities = integration.capabilities as SupplierCapabilities;
  const categories = [...new Set((categoryRows ?? []).map((row) => row.category).filter(Boolean))];
  const errorCode = typeof filters.error === "string" ? filters.error : "";
  const successCode = typeof filters.success === "string" ? filters.success : "";
  const errors: Record<string, string> = { "matterhorn-not-configured": "Matterhorn n’est pas configuré sur le serveur.", "connection-failed": "Le test de connexion a échoué.", "sync-failed": "La synchronisation a échoué.", "integration-not-found": "Cette intégration est introuvable." };
  const successes: Record<string, string> = { "matterhorn-activated": "Matterhorn a été activé.", "matterhorn-already-active": "Matterhorn était déjà actif : aucune duplication créée.", "mock-activated": "Le connecteur mock a été activé.", "mock-already-active": "Le connecteur mock était déjà actif.", "connection-tested": "La connexion fournisseur fonctionne.", "sync-completed": "La synchronisation est terminée." };
  return <div className="mx-auto max-w-7xl">{errorCode && errors[errorCode] && <p role="alert" className="mb-5 rounded-xl border border-[#ead8d3] bg-[#f7ece9] px-4 py-3 text-sm text-[#8a554b]">{errors[errorCode]}</p>}{successCode && successes[successCode] && <p role="status" className="mb-5 rounded-xl border border-[#dce1d8] bg-[#eef1eb] px-4 py-3 text-sm text-[#53664d]">{successes[successCode]}</p>}<Link href="/app/intelligence/fournisseurs" className="inline-flex items-center gap-2 text-sm text-[#74756e]"><ArrowLeft className="size-4" />Supplier Intelligence</Link>
    <header className="mt-5 flex flex-col justify-between gap-5 border-b border-[#e0ded6] pb-7 lg:flex-row lg:items-end"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-3xl font-semibold tracking-[-.03em]">{supplier?.name ?? integration.connector_code}</h1><StatusPill tone={integration.status === "ready" ? "success" : integration.status === "error" ? "error" : "warning"}>{integration.status}</StatusPill><span className="rounded-full bg-[#efeee9] px-2.5 py-1 text-xs">{integration.environment}</span></div><p className="mt-2 text-sm text-[#74756e]">{supplier?.country} · {integration.connector_code}</p></div><div className="flex gap-2"><form action={`/api/supplier-integrations/${id}/test`} method="post"><button className="inline-flex h-10 items-center gap-2 rounded-xl border px-3 text-xs"><ShieldCheck className="size-4" />Tester</button></form><form action={`/api/supplier-integrations/${id}/sync`} method="post"><input type="hidden" name="dryRun" value="false" /><button className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#20211d] px-3 text-xs text-white"><RefreshCw className="size-4" />Synchroniser</button></form></div></header>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_330px]"><main>
      <section className="rounded-2xl border border-[#e0ded6] bg-white p-5"><div className="flex items-center gap-2"><Search className="size-4" /><h2 className="font-medium">Catalogue normalisé</h2></div><form className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><input name="q" defaultValue={q} placeholder="Titre, SKU, EAN, marque…" className="h-10 rounded-xl border px-3 text-sm sm:col-span-2" /><select name="category" defaultValue={category} className="h-10 rounded-xl border px-3 text-sm"><option value="">Toutes catégories</option>{categories.map((item) => <option key={item}>{item}</option>)}</select><select name="stock" defaultValue={stockFilter} className="h-10 rounded-xl border px-3 text-sm"><option value="">Tous les stocks</option><option value="available">En stock</option><option value="low">Stock faible</option><option value="out">Indisponible</option></select><input name="maxPrice" defaultValue={maxPrice || ""} type="number" min="0" placeholder="Prix maximum" className="h-10 rounded-xl border px-3 text-sm" /><input name="maxDelay" defaultValue={maxDelay || ""} type="number" min="0" placeholder="Délai maximum" className="h-10 rounded-xl border px-3 text-sm" /><label className="flex items-center gap-2 text-xs"><input name="eu" value="true" type="checkbox" defaultChecked={filters.eu === "true"} />Expédié depuis l’UE</label><label className="flex items-center gap-2 text-xs"><input name="moq" value="true" type="checkbox" defaultChecked={filters.moq === "true"} />MOQ = 1</label>{capabilities.neutralPackaging && <label className="flex items-center gap-2 text-xs"><input name="neutral" value="true" type="checkbox" defaultChecked={filters.neutral === "true"} />Colis neutre</label>}<button className="h-10 rounded-xl bg-[#eef1eb] px-4 text-sm font-medium">Rechercher</button></form></section>
      <div className="mt-4 grid gap-3">{!products?.length ? <div className="rounded-2xl border border-dashed bg-white p-10 text-center text-sm text-[#777870]">Aucun produit ne correspond aux filtres. Lancez une synchronisation si le catalogue est vide.</div> : products.map((product) => { const score = calculateElrovaProductScore(); const href = `/app/intelligence/fournisseurs/${id}/produits/${product.id}`; const image = firstProductImage(product.images); return <Link key={product.id} href={href} aria-label={`Voir ${product.title}`} className="grid cursor-pointer gap-4 rounded-2xl border border-[#e0ded6] bg-white p-4 transition duration-200 hover:-translate-y-0.5 hover:border-[#c9cec3] hover:shadow-[0_10px_30px_rgba(32,33,29,0.06)] sm:grid-cols-[72px_1fr_auto] sm:items-center"><span className="relative grid size-[72px] place-items-center overflow-hidden rounded-xl bg-[#f1f0ea]">{image ? <Image src={image} alt="" fill sizes="72px" className="object-contain p-1.5 transition duration-200 group-hover:scale-105" /> : <Box className="size-5 text-[#9b9b94]" />}</span><span className="block"><span className="flex flex-wrap items-center gap-2"><span className="font-medium">{product.title}</span><span className="text-xs text-[#888981]">{product.sku}</span></span><span className="mt-2 block text-xs text-[#777870]">{product.brand ?? "Sans marque"} · {product.category} · {product.ships_from_country ?? "Pays inconnu"} · {product.delivery_min_days ?? "?"}–{product.delivery_max_days ?? "?"} j</span><span className="mt-2 block text-xs">Achat <b>{money.format(Number(product.purchase_price_ex_vat))}</b> · Livraison {money.format(Number(product.shipping_cost ?? 0))} · Stock {product.stock} · MOQ {product.moq}</span></span><span className="sm:text-right"><span className="block text-lg font-semibold">{score.score}<span className="text-xs font-normal text-[#888981]">/100</span></span><span className="block text-[10px] text-[#888981]">score provisoire</span><span className="mt-3 inline-flex rounded-xl bg-[#20211d] px-3 py-2 text-xs font-medium text-white transition hover:bg-[#383a34]">Analyser la rentabilité</span></span></Link>; })}</div>
    </main><aside className="space-y-5"><section className="rounded-2xl border border-[#dce1d8] bg-[#eef1eb] p-5"><h2 className="text-sm font-medium">Capacités</h2><div className="mt-4 flex flex-wrap gap-2">{Object.entries(capabilities).map(([key,enabled]) => <span key={key} className={`rounded-full px-2.5 py-1 text-[11px] ${enabled ? "bg-white text-[#53664d]" : "bg-black/5 text-[#92968e]"}`}>{key}</span>)}</div></section>{integration.last_error && <section className="rounded-2xl border border-[#ead8d3] bg-[#f7ece9] p-5"><div className="flex items-center gap-2 text-[#8a554b]"><AlertCircle className="size-4" /><h2 className="text-sm font-medium">Erreur récente</h2></div><pre className="mt-3 whitespace-pre-wrap text-xs">{JSON.stringify(integration.last_error,null,2)}</pre></section>}<section className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-2"><BarChart3 className="size-4" /><h2 className="text-sm font-medium">Synchronisations</h2></div><div className="mt-4 space-y-3">{!runs?.length ? <p className="text-xs text-[#888981]">Aucun historique.</p> : runs.map((run) => <div key={run.id} className="border-t pt-3 text-xs"><div className="flex justify-between"><span>{run.status}</span><time>{new Intl.DateTimeFormat("fr-FR").format(new Date(run.started_at))}</time></div><p className="mt-1 text-[#888981]">{run.products_read} lus · {run.products_created} créés · {run.products_failed} erreurs</p></div>)}</div></section></aside></div>
  </div>;
}
