import Link from "next/link";
import { DatabaseZap, PackageSearch, Plus, RefreshCw, ShieldCheck } from "lucide-react";
import { StatusPill } from "@/components/app/page-shell";
import { getCurrentContext } from "@/lib/auth/current-context";
import { createClient } from "@/lib/supabase/server";
import { syncSupplierCatalog, testSupplierConnection } from "./actions";

export default async function SupplierIntelligencePage() {
  const { workspace } = await getCurrentContext();
  const supabase = await createClient();
  const { data: integrations } = await supabase.from("supplier_integrations").select("*,suppliers(name,country),supplier_catalog_products(count)").eq("workspace_id", workspace.id).order("created_at");
  return <div className="mx-auto max-w-7xl"><header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#75806e]">Supplier Intelligence</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.03em]">Sources d’approvisionnement</h1><p className="mt-2 max-w-2xl text-sm text-[#74756e]">Normalisez les catalogues fournisseurs avant d’analyser leur potentiel commercial.</p></div><Link href="/app/intelligence/fournisseurs/activer" className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-[#20211d] px-4 text-sm font-medium text-white"><Plus className="size-4" />Activer le mock UE</Link></header>
    {!integrations?.length ? <div className="mt-8 grid min-h-72 place-items-center rounded-2xl border border-dashed border-[#d8d6ce] bg-white p-8 text-center"><div><DatabaseZap className="mx-auto size-9 text-[#84907d]" /><h2 className="mt-4 font-medium">Aucune intégration fournisseur</h2><p className="mt-2 max-w-md text-sm text-[#777870]">Activez le connecteur de démonstration pour tester une synchronisation sans secret ni service externe.</p></div></div> :
    <div className="mt-8 grid gap-4">{integrations.map((integration) => { const supplier = Array.isArray(integration.suppliers) ? integration.suppliers[0] : integration.suppliers; const count = Array.isArray(integration.supplier_catalog_products) ? integration.supplier_catalog_products[0]?.count ?? 0 : 0; return <article key={integration.id} className="rounded-2xl border border-[#e0ded6] bg-white p-5 sm:p-6"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><Link href={`/app/intelligence/fournisseurs/${integration.id}`} className="text-lg font-medium hover:underline">{supplier?.name ?? integration.connector_code}</Link><StatusPill tone={integration.status === "ready" ? "success" : integration.status === "error" ? "error" : "warning"}>{integration.status}</StatusPill><span className="rounded-full bg-[#efeee9] px-2.5 py-1 text-xs">{integration.environment}</span></div><p className="mt-2 text-xs text-[#81827b]">{count} produits · Dernière synchronisation {integration.last_successful_sync_at ? new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(integration.last_successful_sync_at)) : "jamais"}</p>{integration.last_error && <p className="mt-2 text-xs text-[#925c52]">Une erreur récente demande votre attention.</p>}</div><div className="flex flex-wrap gap-2"><form action={testSupplierConnection.bind(null, integration.id)}><button className="inline-flex h-10 items-center gap-2 rounded-xl border px-3 text-xs font-medium"><ShieldCheck className="size-4" />Tester</button></form><form action={syncSupplierCatalog.bind(null, integration.id)}><button className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#20211d] px-3 text-xs font-medium text-white"><RefreshCw className="size-4" />Synchroniser</button></form><Link href={`/app/intelligence/fournisseurs/${integration.id}`} className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#eef1eb] px-3 text-xs font-medium"><PackageSearch className="size-4" />Catalogue</Link></div></div></article>; })}</div>}
  </div>;
}
