import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, CircleGauge, ExternalLink } from "lucide-react";
import { EbayResearchButton } from "@/components/product-intelligence/ebay-research-button";
import { getCurrentContext } from "@/lib/auth/current-context";
import { getEbayEnvironment, normalizedMarketplaceListingSchema } from "@/lib/market-intelligence/ebay";
import { calculateEbayObservedProfitability } from "@/lib/product-intelligence/ebay-profitability";
import { estimateProductProfitability } from "@/lib/product-intelligence/profitability";
import { createClient } from "@/lib/supabase/server";

function metricsFrom(value: unknown) { if(!value||typeof value!=="object"||Array.isArray(value)) return null; const item=value as Record<string,unknown>; const number=(key:string)=>typeof item[key]==="number"?item[key] as number:null; return {resultCount:number("resultCount")??0,reliableResultCount:number("reliableResultCount")??0,minimumPrice:number("minimumPrice"),medianPrice:number("medianPrice"),averagePrice:number("averagePrice"),maximumPrice:number("maximumPrice"),averageKnownShipping:number("averageKnownShipping"),freeShippingCount:number("freeShippingCount")??0,newCount:number("newCount")??0,usedCount:number("usedCount")??0,retrievedAt:typeof item.retrievedAt==="string"?item.retrievedAt:null}; }
export default async function ProductAnalysisPage({ params,searchParams }: { params: Promise<{ id: string; productId: string }>; searchParams:Promise<Record<string,string|string[]|undefined>> }) {
  const { id, productId } = await params, feedback=await searchParams;
  const { workspace } = await getCurrentContext(); const supabase = await createClient(); const environment=getEbayEnvironment();
  const { data: product } = await supabase.from("supplier_catalog_products").select("id,title,purchase_price_ex_vat,recommended_retail_price,shipping_cost,currency").eq("id", productId).eq("integration_id", id).eq("workspace_id", workspace.id).maybeSingle(); if (!product) notFound();
  const {data:run}=await supabase.from("marketplace_research_runs").select("*").eq("workspace_id",workspace.id).eq("supplier_catalog_product_id",productId).eq("marketplace","ebay").eq("environment",environment).order("created_at",{ascending:false}).limit(1).maybeSingle();
  const {data:snapshotRows}=run?await supabase.from("marketplace_listing_snapshots").select("normalized_listing,match_score,match_level,reasons,warnings").eq("workspace_id",workspace.id).eq("research_run_id",run.id).order("match_score",{ascending:false}).limit(8):{data:null};
  const snapshots=(snapshotRows??[]).flatMap((row)=>{const parsed=normalizedMarketplaceListingSchema.safeParse(row.normalized_listing);return parsed.success?[{listing:parsed.data,matchScore:row.match_score,matchLevel:row.match_level}]:[];});
  const metrics=metricsFrom(run?.metrics), configured=Boolean(process.env.EBAY_CLIENT_ID&&process.env.EBAY_CLIENT_SECRET);
  const baseline=estimateProductProfitability({supplierPrice:Number(product.purchase_price_ex_vat),shippingCost:product.shipping_cost==null?null:Number(product.shipping_cost),recommendedRetailPrice:product.recommended_retail_price==null?null:Number(product.recommended_retail_price)});
  const ebayAnalysis=metrics?calculateEbayObservedProfitability({reliableCount:metrics.reliableResultCount,medianPrice:metrics.medianPrice,minimumPrice:metrics.minimumPrice,maximumPrice:metrics.maximumPrice,supplierCost:Number(product.purchase_price_ex_vat),supplierShipping:product.shipping_cost==null?null:Number(product.shipping_cost)}):null;
  const money=new Intl.NumberFormat("fr-FR",{style:"currency",currency:product.currency||"EUR"}); const shown=ebayAnalysis?[["Prix fournisseur",money.format(Number(product.purchase_price_ex_vat)),"Fournisseur vérifié"],["Prix de vente prudent",money.format(ebayAnalysis.cautiousSalePrice),"eBay vérifié + prudence ELROVA"],["Marge brute estimée",money.format(ebayAnalysis.grossMargin),"Estimation ELROVA"],["ROI estimé",`${ebayAnalysis.roi.toFixed(1)} %`,"Estimation ELROVA"],["Frais eBay estimés",money.format(ebayAnalysis.ebayFees),`Estimation ${ebayAnalysis.feeConfiguration.version}`],["Livraison fournisseur",product.shipping_cost==null?"Donnée absente":money.format(Number(product.shipping_cost)),product.shipping_cost==null?"Donnée absente":"Fournisseur vérifié"]]:[["Prix fournisseur",money.format(baseline.supplierPrice),"Fournisseur vérifié"],["Prix de vente estimé",money.format(baseline.estimatedSalePrice),"Placeholder ELROVA"],["Marge brute",money.format(baseline.grossMargin),"Placeholder ELROVA"],["ROI",`${baseline.roi.toFixed(1)} %`,"Placeholder ELROVA"],["Frais marketplace",money.format(0),"Placeholder ELROVA"],["Frais livraison",money.format(baseline.shippingFees),product.shipping_cost==null?"Donnée absente":"Fournisseur vérifié"]];
  const error=typeof feedback.error==="string"?feedback.error:"";
  return <div className="mx-auto max-w-6xl"><Link href={`/app/intelligence/fournisseurs/${id}/produits/${productId}`} className="inline-flex items-center gap-2 text-sm text-[#74756e]"><ArrowLeft className="size-4" />Retour au produit</Link><header className="mt-6"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#75806e]">Product Intelligence</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.03em]">Rentabilité de {product.title}</h1></header>
    <section className="mt-7 rounded-2xl border border-[#dce1d8] bg-[#eef1eb] p-6"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-[#6d7b65]">Marché eBay · {environment}</p><h2 className="mt-2 text-xl font-medium">{run?.status==="completed"?(environment==="production"?"Données eBay réelles":"Données API eBay sandbox"):!configured?"eBay non configuré":run?.status==="access_pending"?"Accès eBay en attente":"Analyse non lancée"}</h2>{metrics?.retrievedAt&&<p className="mt-2 text-xs text-[#777e72]">Récupéré le {new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(metrics.retrievedAt))}</p>}</div><form action="/api/market-intelligence/ebay/research" method="post"><input type="hidden" name="integrationId" value={id}/><input type="hidden" name="productId" value={productId}/><EbayResearchButton/></form></div>{error&&<p className="mt-4 rounded-xl bg-white/70 p-3 text-sm text-[#8a554b]">{error==="ebay-not-configured"?"eBay non configuré":error==="ebay-access-pending"?"Accès eBay en attente":"L’analyse eBay n’a pas pu aboutir."}</p>}{metrics&&<dl className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Résultats",metrics.resultCount],["Correspondances fiables",metrics.reliableResultCount],["Prix minimum",metrics.minimumPrice==null?"Non disponible":money.format(metrics.minimumPrice)],["Prix médian",metrics.medianPrice==null?"Non disponible":money.format(metrics.medianPrice)],["Prix moyen",metrics.averagePrice==null?"Non disponible":money.format(metrics.averagePrice)],["Prix maximum",metrics.maximumPrice==null?"Non disponible":money.format(metrics.maximumPrice)],["Livraison moyenne",metrics.averageKnownShipping==null?"Non disponible":money.format(metrics.averageKnownShipping)],["Livraison gratuite",metrics.freeShippingCount],["Neuf / occasion",`${metrics.newCount} / ${metrics.usedCount}`]].map(([label,value])=><div key={String(label)} className="rounded-xl bg-white/75 p-3"><dt className="text-[11px] text-[#777e72]">{label}</dt><dd className="mt-1 text-sm font-semibold">{value}</dd></div>)}</dl>}</section>
    <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{shown.map(([label,value,source])=><section key={label} className="rounded-2xl border border-[#e0ded6] bg-white p-5"><p className="text-xs text-[#85867f]">{label}</p><p className="mt-3 text-2xl font-semibold">{value}</p><p className="mt-2 text-[10px] uppercase tracking-wide text-[#8a8b84]">{source}</p></section>)}</div>
    <section className="mt-6 rounded-2xl border border-[#e0ded6] bg-white p-6"><h2 className="text-lg font-medium">Annonces comparables</h2>{snapshots.length===0?<p className="mt-4 text-sm text-[#777870]">Aucune annonce fiable disponible.</p>:<div className="mt-4 grid gap-3">{snapshots.map(({listing,matchScore,matchLevel})=><article key={listing.externalId} className="grid gap-4 rounded-xl border border-[#ebe9e2] p-3 sm:grid-cols-[64px_1fr_auto] sm:items-center"><div className="relative grid size-16 place-items-center overflow-hidden rounded-lg bg-[#f1f0ea]">{listing.imageUrl?<Image src={listing.imageUrl} alt="" fill sizes="64px" className="object-contain"/>:<span className="text-[10px] text-[#999a93]">Sans image</span>}</div><div><p className="text-sm font-medium">{listing.title}</p><p className="mt-1 text-xs text-[#777870]">{money.format(listing.price)} · Livraison {listing.shippingCost==null?"inconnue":money.format(listing.shippingCost)} · Total {listing.totalDeliveredPrice==null?"inconnu":money.format(listing.totalDeliveredPrice)}</p><p className="mt-1 text-xs text-[#777870]">{listing.condition??"État inconnu"} · {listing.sellerUsername??"Vendeur inconnu"}</p></div><div className="sm:text-right"><p className="text-sm font-semibold">{matchScore}/100</p><p className="text-[10px] text-[#888981]">{matchLevel}</p>{listing.itemWebUrl&&<a href={listing.itemWebUrl} target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1 text-xs font-medium text-[#586451]">Voir eBay <ExternalLink className="size-3"/></a>}</div></article>)}</div>}</section>
    <section className="mt-6 rounded-2xl border border-[#dce1d8] bg-[#eef1eb] p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#20211d] text-white"><CircleGauge className="size-5"/></span><div><p className="text-xs text-[#6f786a]">Confiance de rentabilité</p><p className="text-xl font-semibold">{ebayAnalysis?.confidence??"Insuffisante"}</p></div></div><p className="mt-4 text-sm text-[#687064]">Les correspondances faibles sont exclues des calculs. Trois correspondances exactes ou fortes sont nécessaires.</p></section></div>;
}
